#!/usr/bin/env bash

set -e
source $(dirname $(realpath $0))/../CUSTOM_INFO

# a docker image tag with the format 'name:tag'.
# generated by CUSTOM_INFO above.
# eg: alexlee/test-a:latest
IMGTAG=${USERNAME:-$(id -un)}/${IMGNAME:-"test-a"}:${VERSION:-"latest"}

install_prefix=$HOME/.local
[[ ! -d $1 ]] || install_prefix=$(realpath $1)

install_path=${install_prefix}/docker_env

[[ -d $install_path ]] || mkdir -p $install_path

FUNC_NAME=${FUNC_ALIAS:-${ENTRY:-bash}}

install_name=${FUNC_NAME##*/}_${IMGNAME:-"test-a"}_env

install_path=${install_path}/${install_name}

cat <<EOF > ${install_path}
docker_${FUNC_NAME##*/}() {
    docker run \\
        -it \\
        --rm \\
        -u $(id -u) \\
        --entrypoint ${ENTRY} \\
        -v /home/\${USERNAME}:/home/\${USERNAME} \\
        -v /media:/media \\
        --hostname ${IMGNAME:-"test-a"} \\
        -w \$(realpath \$(pwd)) \\
        -e REPO_URL=\${REPO_URL:-'https://gerrit-googlesource.proxy.ustclug.org/git-repo'} \\
        ${IMGTAG} \\
        \$@
    }

repo-init() {
local REPO_URL='https://gerrit-googlesource.proxy.ustclug.org/git-repo'
\${REPO:-"docker_${FUNC_NAME##*/}"} init \$@
}

repo-sync() {
local REPO_URL='https://gerrit-googlesource.proxy.ustclug.org/git-repo'
while true
do
    \${REPO:-"docker_${FUNC_NAME##*/}"} sync -c --no-tags --no-clone-bundle -j\`nproc\`
    [[ \$? -ne 0 ]] || break
done
}

PASS=$RANDOM
if [[ "\${BASH_ARGV0##*/}" != "${install_name}" ]]; then
    bash \${BASH_ARGV} \${PASS};
elif [[ "\${BASH_ARGV}" == "\${PASS}" ]]; then
    echo -e "\033[1;3;32m""command available:""\033[0;34m"
    typeset -f | awk '/ \(\) \$/ {print " \033[1;32m"\$1"\033[0;34m"}'
else
    echo -e "\033[1;3;32m""USAGE:""\033[0;34m"
    echo -e "\$ \033[1;32m""source \${BASH_ARGV0}""\033[0;34m"
fi
EOF

echo -e "First, exec: \n\
    source $install_path"
echo -e "Then, use: \n\
    docker_${FUNC_NAME##*/} [arg1]..."

echo -e "you can also use *repo-init* for docker_${FUNC_NAME##*/} init, e.g.\n\
    repo-init -u <git_repo>  -b <branch> -m <manifest_xml>\n\
and\n\
    *repo-sync* for docker_${FUNC_NAME##*/} sync\n\n\
their are little differences between them, check the definitions by:\n\
    type repo-init\n\
    type repo-sync"
